[window]
dimensions = { columns = 100, lines = 28 }

decorations = "None"
padding = { x = 10, y = 10 }
opacity = 0.9

[font]
normal = { family = "JetBrains Mono NF", style = "Regular" }
size = 12.0

[cursor]
# Block, Underline, Beam
style = { shape = "Block", blinking = "Never" }

[colors]
[colors.primary]
foreground="0xffffff"
background="0x0a0a0a"

[colors.normal]
black   = "0x000000"
red     = "0xcc0403"
green   = "0x19cb00"
yellow  = "0xcecb00"
blue    = "0x0d73cc"
magenta = "0xcb1ed1"
cyan    = "0x0dcdcd"
white   = "0xdddddd"

[colors.bright]
black   = "0x767676"
red     = "0xf2201f"
green   = "0x23fd00"
yellow  = "0xfffd00"
blue    = "0x1a8fff"
magenta = "0xfd28ff"
cyan    = "0x14ffff"
white   = "0xffffff"
